### ISSUE TITLE
ui-server: tagged version is pointing to staging server

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-ui#122]
![Image](https://github.com/mint-o-badges/badgr-ui/assets/40634685/dd149cce-b9f2-4638-aa31-f9e90590854b)

**Comment by mpfeil** [comment]
I guess the issue here is that two images are build. Metadata is extracted once for the `build-and-push-image` step and on an tagged version it will generate two tags: `v0.4.2` and `latest` on a none tagged version it would be `pr-xxx`.

[This step](https://github.com/mint-o-badges/badgr-ui/blob/main/.github/workflows/registry-build-publish.yml#L66) is building and pushing an image with the following tags: `v0.4.2` and `latest`.

Just some seconds or minutes later the `staging` [step](https://github.com/mint-o-badges/badgr-ui/blob/main/.github/workflows/registry-build-publish.yml#L73) is building an image with the following tags: `v0.4.2` and `latest-Staging`.

Pushing the image with the tags overwrite the `v0.4.2` tag on the registry because it is already existing.

**Comment by timber-they** [comment]
Oooh and with multiple tags it's a string so that only the last tag gets the postfix

**Comment by mpfeil** [comment]
I guess we are building different images because of Angular´s `environment` mechanism.

Just an idea because it is a common problem and in my opinion it is easier to build an image once and to have the option to pass in environment variables to configure the app.
Found this one on the web: https://mokkapps.de/blog/how-to-build-an-angular-app-once-and-deploy-it-to-multiple-environments

Maybe solution 2 or 3 might be a good idea.
