### ISSUE TITLE
ui: use productive AI endpoint

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#138]
Apparently, only the port has changed, the rest stays the the same: http://49.12.65.167:3001/

**Comment by timber-they** [comment]
I adjusted it on the servers, feel free to test it, but there's no codebase changes that can be reviewed.

**Comment by zven** [comment]
At least on staging, nothing happens when I click on "Passende Kompetenzen vorschlagen"

Sending a request directly to the server works:

```
curl --request POST \
 --url 'http://49.12.65.167:3001/recommendations/chats?api_key=a61d2acd-de1b-48d5-a3a2-9f41c8f0b47e' \
 --header 'Content-Type: application/json' \
 --data '{
  "text_to_analyze" : "Dieser Kurs ist für alle geeignet, die gerne mehr zum Thema erfahren  und ins Handeln kommen möchten. Für Lehrende und MINT-Bildungsakteur:innen haben wir einen separaten und umfangreicheren Kurs erarbeitet, der auch Handlungsempfehlungen sowie didaktische Beispiele für die Schule und außerschulische Lernorte beinhaltet. Jedoch eignet sich dieser Kurs auch für den Einsatz im Unterricht mit  Schüler:innen."
}'
```

**Comment by timber-they** [comment]
@zven yes this seems to be the same as #160. However, it has nothing to do with the productive endpoint, but rather with our implementation: It seems we can't handle üäö yet. Maybe I'll work on it in the other ticket then?

**Comment by zven** [comment]
@timber-they I see. Then we should address this in another ticket (e.g. that one: https://github.com/mint-o-badges/badgr-ui/issues/160). 👍

**Comment by zven** [comment]
@timber-they Did you also update the config for the staging environment or has something changed in between? Atm, the staging system seems to be talking to the mock backend.

**Comment by timber-they** [comment]
I can't reproduce this. However, it is a bit hard to test because apparently now with short texts the AI endpoint returns an error saying that the text is too short. This is new, though, and thus we don't handle it properly yet. With longer texts however the AI tool doesn't work with the state that's currently deployed on Staging, since the PR for the fix isn't reviewed yet. I suggest to create a separate ticket for handling the new error of the AI endpoint properly and closing this ticket again, except if you still have reasons to believe that Staging is talking to the mock backend, @zven.

**Comment by zven** [comment]
Very curious, now it works!

**Comment by timber-they** [comment]
I created the issue #203 for the short text problem.
