### ISSUE TITLE
Create badge: Criteria are not fully displayed

### ISSUE THREAD

**Issue by IngaSchmidt** [mint-o-badges/badgr-ui#158]
**Name the test case**
Create badge

**Describe the bug**
Criteria are not fully displayed. The last letter is automatically deleted.

**To Reproduce**

1. Go to 'Create badge'
2. Scroll down to 'criteria'
3. Click on "Create Badge"
4. See error in the "criteria" field

**Expected behavior**
the whole word

**Screenshots**
<img width="181" alt="image" src="https://github.com/mint-o-badges/badgr-ui/assets/164493443/d8a77724-355d-4ffa-86b1-4e62589fa025">

**Desktop (please complete the following information; remove if not applicable):**
OS: Windows 11
Browser: Microsoft Edge
Version 123.0.2420.65

**Comment by TobiSchumacher** [comment]
I have the same problem on my Huawei Mate Lite 10 (Android) and it happens when I look at the badge as an earner in my rucksack...:

![Screenshot_20240408-173740](https://github.com/mint-o-badges/badgr-ui/assets/164183217/0789ac52-605e-4483-b681-c449dff28c35)

....and also after editing a badge as an issuer:

![Screenshot_20240408-171835](https://github.com/mint-o-badges/badgr-ui/assets/164183217/c1a3c60a-8819-49a9-89f7-cae238853d26)

**Comment by zven** [comment]
Okay, that does not look okay. We should either
- display the whole text
- or add `...` in the end in case we short any text in this view
