### ISSUE TITLE
ui: enable users to delete their accounts

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#421]
Users are not able to delete their accounts at the moment. We should add an option to the profile view for deleting you user.

Open questions:

- What happens to related institutions and badges (and assertions) when a user is deleted? 

Todos:

- [x] add button do to profile view
- [x] delete user

**Comment by timber-they** [comment]
Regarding the institutions: Since I seem to have misunderstood [this ticket](https://github.com/orgs/mint-o-badges/projects/2/views/1?pane=issue&itemId=61688916), once it is merged the behavior of institutions where the creator is deleted will be well defined: The user related to the institution with the highest privileges will be assigned as new "creator" and it's role will be changed to owner. It can of course be adjusted, if different behavior is required.

In my understanding this is the only relevant part regarding institutions (right?), so the only open question would be regarding the behavior of badges and assertions.

**Comment by timber-they** [comment]
Regarding the badges / assertions: Nothing is deleted, so to everyone except the deleted user it looks exactly the same as before.

Is this enough information regarding the open questions, @zven? Then I could start working on that.

**Comment by zven** [comment]
@timber-they Thanks for the input!

1. In the light of https://github.com/mint-o-badges/badgr-server/issues/181: What happens if the user is deleted but the sole member of an institution? Is the institution removed as well? If yes: What happens to the badge classes that were created: Are they also removed? To my understanding, deleting a badge class is only possible once you've revoked all awarded badges.

2. Just to make sure that I understand your previous post correctly: If I would delete my user, the badges I've been awarded (= assertions?) are still in the system?

**Comment by timber-they** [comment]
1. No. The institution ("issuer") remains in the system, it just has no user assigned anymore. This behavior could be adjusted, of course.
2. Exactly.

**Comment by zven** [comment]
@timber-they 
1. Then I'd suggest to simply change the state of that institution to "unverified" when there is no user in the system anymore. This way the instition itself is hidden and the public view of the badge (as reachable for example via https://staging.openbadges.education/catalog/badges) does not show the badge class anymore.
2. Okay, sounds legit as well.

**Comment by timber-they** [comment]
TODOs:
- [ ] Add delete button to profile view
- [ ] Delete user
- [ ] Unverify institution when all its users are deleted

**Comment by timber-they** [comment]
There are two PRs: [Server](https://github.com/mint-o-badges/badgr-server/pull/200) and [UI](https://github.com/mint-o-badges/badgr-ui/pull/534).
