### ISSUE TITLE
CSV-Page (Bulk Award) Page

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#486]
Page: Badge an mehrere Lernende gleichzeitig vergeben

- I think "Evidence" ist not easy understandable, can we use another word?
- please add the comma bevor "um": "... Beispiel-Vorlage, um..." and add period at the end of the sentence
![Bildschirmfoto 2024-07-15 um 11 49 09](https://github.com/user-attachments/assets/0821472d-01a3-47de-920a-cadf1611c6d3)

**Comment by zven** [comment]
After having numerous discussions we came up with a design and wording that hopefully works. Once the design is ready to be implemented, @Annicelia, please link it here in the comments section.

Furthermore, we need to adjust a number of smaller things:
- [ ] update the example file (see below)
- [ ] support additional colum name auto detection for `name` (also support `Vor-/Nachname`) and `email` (also support `E-Mail-Addresse`)
- [ ] in addition to a `,` we must also support a `;` as a column separator since some spreadsheet tools (looking at you, Numbers...) let you only export as `csv` with `;` as a separator 🙄

**Comment by Annicelia** [comment]
@zven is ready: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=2887-6935&t=37wTsKjXWeglAhPo-4
Could we give the example file a name like "CSV-Beispiel-Vorlage" ? I think that would make it look more trustworthy to users :)
