### ISSUE TITLE
ui: exclude linking to ESCO skills for manually added competencies

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#610]

**Comment by timber-they** [comment]
Could you link the PR for this?

**Comment by jona159** [comment]
I linked it, but i wanted to merge into #589, not into main. Maybe @YouQam can review this

**Comment by zven** [comment]
I'm currently in the process of figuring out the details.

**Comment by zven** [comment]
@jona159 and @timber-they 
mycelia and me discussed how to handle ESCO competencies that were added via the AI tool vs. manually added competencies:
 
- The users shall not be able to edit competencies that were added with the ai tool.
- Only manually added skills can be edites afterwards.
- For manually added skills, one should not be able to provide a link / identifier.

For this to work properly, would need to save some additional information.
- save the `source` of skill (e.g. `ai-tool` or `manual`)
- save the `framework` (atm: either blank or `esco`)
- to make things more flexible for the future: change `esco-id` (if that was the name) into `framework-identifier` where we store the whole identifier (atm only: `esco/skill/7de3b70e-2568-420a-8528-69523d323e7a`, better: `http://data.europa.eu/esco/skill/7de3b70e-2568-420a-8528-69523d323e7a`)
- This way, we could support different educational standards in the future (with different / new values for `source`, `framework` and `framework-identifier`)
- If we adjust the data model, we'd also need to migrate the existing esco skills.

Do those ideas make sense to you? Shall we expand this issue to address those changes or shall we rather open a new issue?

**Comment by timber-they** [comment]
@zven I don't quite understand why manually added skills should not be able to provide a link / identifier. Other than that the modifications seem to make sense and it shouldn't be tooo big of a change. We do of course have to be a bit careful with not breaking anything in the migrations.

I think it makes sense to open a new ticket for it, but I don't have a strong opinion on that.

**Comment by zven** [comment]
@timber-they Leaving out the identifier URI for manually added competencies was a requierement from mycelia since it would confuse users. Manually added skills would not count as "proper" esco skills, hence not identifier.

**Comment by jona159** [comment]
server: https://github.com/mint-o-badges/badgr-server/tree/feat/update-competency-json-command
ui: https://github.com/mint-o-badges/badgr-ui/tree/feat/handle-competency-framework

**Comment by jona159** [comment]
In the server PR a new django management command is introduced to update the existing competencies to the new schema. 
To test it please run: 
```
docker compose exec api /bin/bash 
python manage.py update_extensions
``` 
To test it without actually modifying the values in the database, add the ```dry-run``` flag to the last command.
 It will print out how the json _would_ look like after the command. 

In the backend i also installed the ```django-dbbackup``` package in order to make a database backup before updating the competencies. 
To create the backup run: ```python manage.py dbbackup``` 
List backups with: ```python manage.py listbackups```
To apply the backup run: ```python manage.py dbrestore``` (optionally specify filename with ```--input-file``` )

**Comment by timber-they** [comment]
This ticket got blown up a bit. Is it still a requirement that @YouQam should review this? Also note that your links don't point to PRs but to branches. Could you thus also confirm that this ticket is actually ready to be reviewed?

**Comment by jona159** [comment]
@timber-they yes it is ready to be reviewed, i updated the links

**Comment by zven** [comment]
Something that came to my mind regarding the migration: For an unrelated issue, I looked into the database and found `escoID`s in three different shapes (moste likely done due to manual editing etc.).

All the same skill on the esco plattform:
`http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d`
`/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d`
`https://esco.ec.europa.eu/de/classification/skills?uri=http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d`

How are we handling those?

**Comment by timber-they** [comment]
I assume that @zven s question should be handled before review?

**Comment by zven** [comment]
@timber-they I'm not entirely sure if we should fix this as part of this issue or even _can_ fix it, but we should at least discuss the implications before we migrate to our new data model for the competencies.

**Comment by jona159** [comment]
I updated the script to transform each case into an identifier of this format: 
```http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d```

**Comment by zven** [comment]
@jona159 Does your script support a dry run functionality? I stumbled across some cases, where users changed some competencies retroactively, wich lead to some odd behaviour: https://github.com/mint-o-badges/badgr-ui/issues/794

**Comment by timber-they** [comment]
I'm confused by this ticket. There's been a lot of back and forth. The PR however only has very few changes, most of which seem to duplicate things. What's going on here?

**Comment by zven** [comment]
Aim of this issue was to enable us to distinguish between different types of skills. With the current data model, we don't make a difference between the ESCO skills coming from the AI tool and manually addes skills. Existing ESCO skills (coming from the AI tool) can be edited later as well (and thus create ). In addition, you can also manually add ESCO identifiers (in basically any format, let it be the whole ESCO URI or just the identifying last bits) to a manually addes skill.

This led to a wild mix of AI skills that were edited afterwards and manually added skills that, due to the presence of an ESCO URI, _looked_ like "official" ESCO skills. As a result, the competency view in the backpack is rather messy and ESCO links quite often led to nowhere.

This issue consists of two parts:

Server:
* update the data model
* create a script that migrates the existing skills and supports this process (e.g. with a dry run option)
* enable database backups (should be run before the migration in case we break something) 

UI:
* when editing competency badges, make the ESCO skills read only
* allow editing only for manually added skills

**Comment by Thiemann96** [comment]
you can link 2 PR's here by mentioning `#766` in the respective pr's (see my card for #808 )
