### ISSUE TITLE
server: PDF-Zertifikat

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#689]
On staging, it currently looks like this:
![Bildschirmfoto 2024-09-09 um 11 04 36](https://github.com/user-attachments/assets/e8e8dac6-428b-41e3-9fc6-71f0cc5e8b90)

It would be great if the title of the competency and the time stamp would be centred inside each competency-frame and the title would not run into the time indication but breaks into the next line. 
And it looks like the font is way bolder as in the wireframe? I used Rubik Medium, size 12
<img width="523" alt="Bildschirmfoto 2024-09-09 um 11 05 38" src="https://github.com/user-attachments/assets/b9cc6c59-fe63-4423-871b-5676969d9460">

**Comment by jona159** [comment]
@Annicelia i made some adjustments, it would now look like this: 
![kompetenzen-überarbeitung](https://github.com/user-attachments/assets/6977c710-8284-469c-8f71-a5e714acfbb1)
If you could provide this clock icon that is used in your design as a png, i could integrate it as well instead of using the current clock
