### ISSUE TITLE
ui | server: pull request to release branch leads to conflicts

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#699]
This is very odd and we should resolves this.

**Comment by timber-they** [comment]
So I've played around a bit in a test repository and seems that this is because we *squash* and merge our release committs.
So what happens is this:
- We commit some things to `main`, say changes to file `a` and `b` (in commits `A` and `B`)
- We create a release by squashing and merging those changes to `release`.
- Now on `main` there are the commits `A` and `B`, and on release the commit `AB` (squashed)
- Now we change some things on `main` again, this time to files `a` and `c` (in commits `A2` and `C`)
- If we now want to (squash) merge this into `release` for a second release, `git` sees that there's a commit (`AB`) on `release`, that's not on `main`, that made changes to files `a` and `b`. This means however, that an automatic merge is not possible, because on branch `main` there's two commits (`A2` and `C`) that are not on `release`, but made changes to the files `a` and `c` - so **also** to `a`!
- So both branches have changes to file `a` that are not on the other branch, which is a merge conflict.

If instead we don't squash but *just* merge onto `release`, the situation would be different. Because then the commit on `release` that made changes to `a` would be `A` - which is also on `main`! So there's no merge conflict. The same *should* be true for rebasing.

**Comment by zven** [comment]
At least we don't seem to be the only ones struggling with this. If 3. (merge queue) turns out to be too sketchy for your taste, I'd suggest we take the manual route as outlined in 1. (after doing the whole delete and recreate cycle one more time)

**Comment by timber-they** [comment]
We decided to use the merge queue.
