### ISSUE TITLE
server: update badge pdf design

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#716]
New designs for badge pdfs see here on figma: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=8108-18789&t=jxKvW1OdyNKDETUu-4

**Comment by Thiemann96** [comment]
My PR can be found [here](https://github.com/mint-o-badges/badgr-server/pull/276). The relevant PR for the UI is [here](https://github.com/mint-o-badges/badgr-ui/pull/802) 
 
Some thoughts: 

I had to remove `@authentication_classes([TokenAuthentication, SessionAuthentication, BasicAuthentication])` because otherwise the route would only return a 403 error. The route still needs a Bearer token so its still authenticated. 

 [Similar routes](https://github.com/mint-o-badges/badgr-server/blob/071dbc4c1f5ca4097b17909565ba7ec3e5c6391a/apps/mainsite/views.py#L354) in the existing codebase seem to have the same problem and **not** provide `@authentication_classes([TokenAuthentication, SessionAuthentication, BasicAuthentication])`

A [comment](https://github.com/mint-o-badges/badgr-ui/blob/91e6c66d05476c8181d18df64e62ef7edcf156d0/src/app/common/services/ai-skills.service.ts#L32) in the UI seems to hint at a similar problem

**Comment by Thiemann96** [comment]
QR Code creation is now done in the backend. The PR for UI becomes obsolete. The new PR for back end is [#281](https://github.com/mint-o-badges/badgr-server/pull/281)
