### ISSUE TITLE
ui | server: show version on website and api page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#769]
At the moment, we have no way of knowing which version is currently deployed on `prod`, `staging` or `release`. After discussing with @umut0 it would make sense to have information on the current version:

On the OEB website we could put in in the very bottom of the imprint page: https://staging.openbadges.education/public/impressum
For the server, this could be on the api documentation pages: https://api.openbadges.education/docs/v2/ https://api.openbadges.education/docs/v1/ 

First ideas:
 
* use github tags and releases
* automatic version incrementing that makes sense (I think we have something like this already but don't really use it)

**Comment by timber-they** [comment]
So currently we automatically deploy the latest package automatically. I imagine that the following options should be possible:
- Get the commit hash from the package that is currently deployed and display that in the footer (e.g. `67c7137b5f7c7ee77b06203e5142e9e55ea607f4`, or in short `67c7137`). This information is contained in the package and can be retrieved with `docker image inspect ghcr.io/mint-o-badges/badgr-ui:develop-Develop | grep "org.opencontainers.image.revision" | sed -E "s/^\\W*\"org.opencontainers.image.revision\": \"([0-9a-f]+)\".*/\1/g"` or `docker image inspect ghcr.io/mint-o-badges/badgr-ui:develop-Develop | grep "org.opencontainers.image.revision" | sed -E "s/^\\W*\"org.opencontainers.image.revision\": \"([0-9a-f]{7})[0-9a-f]+\".*/\1/g"` respectively. Then we would just somehow need to integrate it into the webpage
- Get the tag of the most recent commit that is not newer than the commit from the package that is currently deployed. This information should be available since we already know how to get the commit that is currently deployed
- Change the way we deploy stuff so that we only deploy if a commit gets tagged. Than extract that tag information
- Add some version information in the code (or actually use it, I *think* we already have something like this) and display that. That would mean that we manually need to update the version information though. That would be the easiest to execute, but it would involve more manual steps

**Comment by zven** [comment]
I'm strongly gravitating to suggestion 1. (display commit hash) or 3. (deploying things once we tag a commit). Could 3. be realized in a way that we _don't_ need to increment / create tags manually? No 1. sounds nicely simple.
We could also check out how the opensensemap does that: https://opensensemap.org/about It looks like a compination of versioning and commit hash.

@umut0 What do you think?

**Comment by timber-they** [comment]
@zven yes opensensemap seems a good inspiration! From the code, this is the relevant part:
```js
            {
              match: "VERSION",
              replacement: "<%= pkg.version %>",
            },
            {
              match: "NAME",
              replacement: "<%= OPENSENSEMAP_RELEASE_NAME %>",
            },
            {
              match: "REVISION",
              replacement: "<%= gitinfo.local.branch.current.shortSHA %>",
            },
```

So there seems to be a package version (that is independent of git) and the git short commit hash. I'm gonna look into how we could integrate the git hash then.

**Comment by timber-they** [comment]
There is an [angular schematic](https://github.com/w11k/angular-git-info/tree/master) that gives us all the information we need. I've integrated it into [this branch](https://github.com/mint-o-badges/badgr-ui/tree/feat/show-version-on-website-and-api-page). what it does is create an environment file in `src/environment/version.ts` with all the relevant `git` information. Since we build every time we deploy, this gets updated automatically. Right now for example it looks like this:
```ts
// IMPORTANT: THIS FILE IS AUTO GENERATED! DO NOT MANUALLY EDIT OR CHECKIN!
/* tslint:disable */
/* eslint-disable */
export const VERSION = {
    "dirty": true,
    "raw": "v1.4.0-162-ge382db90-dirty",
    "hash": "ge382db90",
    "distance": 162,
    "tag": "v1.4.0",
    "semver": {
        "options": {
            "loose": false,
            "includePrerelease": false
        },
        "loose": false,
        "raw": "v1.4.0",
        "major": 1,
        "minor": 4,
        "patch": 0,
        "prerelease": [],
        "build": [],
        "version": "1.4.0"
    },
    "suffix": "162-ge382db90-dirty",
    "semverString": "1.4.0+162.ge382db90",
    "version": "0.0.0"
};
/* tslint:enable */
```
Note that it contains the short `git` commit hash of the latest commit (though for some reason there's a `g` added at the beginning, but we can truncate that), and it *also contains the latest tag*!
So we can simply decide to tag release commits (or any commit in between) and then the displayed version also gets updated. If we don't tag it, the version stays the same, but the commit hash still indicates which version we're on.

**Comment by timber-they** [comment]
I've also added a similar mechanism to retrieve the `git` commit hash and latest tag in the server. You can check it out on [this branch](https://github.com/mint-o-badges/badgr-server/tree/feat/show-version-on-website-and-api-page). It's a bit more complicated and I still need to test it on our servers, but it seems to work.

**Comment by timber-they** [comment]
We decided to make the UI version available in the imprint and the server version available in the staff interface, as well as in the imprint of the UI (via an API request to the server).

**Comment by timber-they** [comment]
[Server PR](https://github.com/mint-o-badges/badgr-server/pull/267)   
[UI PR](https://github.com/mint-o-badges/badgr-ui/pull/781)

**Comment by zven** [comment]
@timber-they and @YouQam The `g` actually seems to be there for a reason: https://stackoverflow.com/questions/23939214/why-does-git-describe-prefix-the-commit-id-with-the-letter-g 

For our purpose at the moment (making transparent what is deployed in the UI) and withouth any further automation based on the git commit hash, I'd actually suggest we omit the extra `g`.

**Comment by timber-they** [comment]
This does not seem to work with the automatic deployment (I couldn't test it on `develop` because it was constantly in use). So I'm reopening this ticket.

**Comment by YouQam** [comment]
> This does not seem to work with the automatic deployment (I couldn't test it on `develop` because it was constantly in use). So I'm reopening this ticket.

There's a new ticket for automate automatic https://github.com/mint-o-badges/badgr-ui/issues/787

**Comment by jona159** [comment]
@timber-they i guess ```develop```would be free to use now

**Comment by timber-they** [comment]
New [Server PR](https://github.com/mint-o-badges/badgr-server/pull/277) and [UI PR](https://github.com/mint-o-badges/badgr-ui/pull/810).
