### ISSUE TITLE
ui: visual learning path creation

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#790]
Atm, we create learning paths by uploading a JSON-file (as implemented in #564). Next iteration will be implementing a UI based editor for issuers.

**Comment by zven** [comment]
Designs currently WIP.

**Comment by zven** [comment]
The *preliminary* design can be found here: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=9259-17017&t=RnmTQwnFKD1QwBLf-4 

@Annicelia will post the final design here once it's done.

**Comment by Annicelia** [comment]
(_and just FYI_, maybe it is valuable information when designing the page: we are planning to optimise the badge creation page at a later date and I will adapt the input fields so that they look like they do now in the learning path editor. the design is work in progress but will look something like this: 
![Bildschirmfoto 2024-10-29 um 20 01 53](https://github.com/user-attachments/assets/d9ec34ce-c52e-401d-b57f-bb5ad901b5ac)

**Comment by zven** [comment]
Update:

- [ ] make duration for badges mandatory
- [ ] allow only those badges to be added to a learning path that have a duration > 0

**Comment by Annicelia** [comment]
@jona159 [Badge-Design-Vorlagen.zip](https://github.com/user-attachments/files/17901202/Badge-Design-Vorlagen.zip)
