### ISSUE TITLE
ui: adjust page width, sizing and spacing of cards

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#858]
Atm, we have three types of cards:

* badges
* institutions
* learning paths

In some cases, the horizontal and vertical spacing is not equal. It would look nicer if it were.

**Comment by zven** [comment]
@Annicelia Shall we use the same spacing for all three card categories? And should / can that spacing change with screen resp. card size?

**Comment by Annicelia** [comment]
@zven yes, please use the same spacing for all cards – I created this issue (https://github.com/mint-o-badges/badgr-ui/issues/876) as well for standardizing alle the overview pages. in my design, the spacing is 24px which works with the size of the cards and the grid/columns. 
![Bildschirmfoto 2024-11-25 um 09 25 51](https://github.com/user-attachments/assets/cc78476d-83c1-46f0-ae2a-1872186c3514)
Figma link: https://github.com/mint-o-badges/badgr-ui/issues/876
I adapted the size of the institution cards as well so that they have a fixed height: 
![Bildschirmfoto 2024-11-25 um 09 39 42](https://github.com/user-attachments/assets/39868af6-58cf-4cdb-b091-c23c969e908e) I will do the same for the Lernpfade-Cards so that wie don't have a problem with differing heights of the cards. 
The spacing can change with responsive but please make sure it is not to small.

**Comment by zven** [comment]
@Annicelia Spacing between all cards should be `24 px`, right?

**Comment by zven** [comment]
@umut0 and @Annicelia discussed the topics page / content width, responsive cards (dynamic resizing) and spacing of cards. We'll update the page with and adapt / fix what breaks in the UI afterwards.

**Comment by umut0** [comment]
I will also unify the headlines as in the designs.
